services:
  code-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=100
      - PASSWORD=P@ssw0rd
    volumes:
      # - ./config:/config
      - .:/config/workspace
      - /home/ec2-user/.aws:/config/.aws:ro
    ports:
      - 8080:8443
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    # runtime: nvidia  # For backward compatibility if needed
    # restart: unless-stopped
